version: '3'

services:
  angle-calculator:
    build:
      context: .
      dockerfile: ./angle-calculator.dockerfile
    ports:
      - target: 8001
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - DISPLAY=:1
      - LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  cone-detector:
    build:
      context: .
      dockerfile: ./cone-detector.dockerfile
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  OpenDLV-Vehicle-View:
    build:
      context: .
      dockerfile: ./OpenDLV-Vehicle-View.dockerfile
    ports:
      - target: 80
        published: 8080
        protocol: udp
      - target: 81
        published: 8081
        protocol: udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - UDP_PORT_IN=8080
      - UDP_PORT_OUT=8081

  opendlv-video-h264-decoder:
    build:
      context: .
      dockerfile: ./opendlv-video-h264-decoder.dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: udp
      - target: 8081
        published: 8081
        protocol: udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
