version: '3'

services:
  OpenDLV-Vehicle-View:
    image: chrberger/opendlv-vehicle-view:latest
    command: ["--init", "-i", "--net=host"]
    volumes:
      - $PWD:/opt/vehicle-view/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 8080
        protocol: udp
      - target: 81
        published: 8081
        protocol: udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - UDP_PORT_IN=8080
      - UDP_PORT_OUT=8081

  opendlv-video-h264-decoder:
    image: h264decoder:v0.0.5
    command: >
      sh -c "xhost + && echo 'Avkodar för Daimstruten...' &&
      docker run --rm -ti --net=host -e DISPLAY=$DISPLAY -v /tmp:/tmp --ipc=host"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  cone-detector:
    image: einerr/daimstruten:latest
    command: ["--cid=253", "--name=img", "--width=640", "--height=480", "--verbose"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - DISPLAY=:1
    volumes:
      - /tmp:/tmp
    ipc: host
    network_mode: host

  angle-calculator:
    image: baoq/fisherman:latest
    command: ["--width=640", "--height=480"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - DISPLAY=:1
      - LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

